version: "3"
services:
    mariadb:
       image: "mariadb:10.7"
       restart: always
       ports:
         - "3306:3306"
       volumes:
           - ./docker/mariadb:/docker-entrypoint-initdb.d
       environment:
         - MARIADB_ROOT_PASSWORD=password
         - MYSQL_PASSWORD=password
         - MYSQL_USER=user
         - MYSQL_DATABASE=ecommerce
    adminer:
        image: adminer
        restart: always
        ports:
           - 8082:8080

